### ISSUE TITLE
ActiveForm field render order

### ISSUE THREAD

**Issue by marqu3s** [yiisoft/yii2-bootstrap#120]
Hello!
I was debuging a space between a checkbox, it's label and a text hint and then I found out that when rendering the hints for the checkbox Yii Bootstrap ActiveForm is rendering it in a different order then a text input field with hint enabled. Chek this out.

```php
<?= $form->field($article, 'title')->hint('Textfield Hint') ?>
<?= $form->field($article, 'active')->checkbox()->hint('Checkbox Hint') ?>
```

The following HTML code is rendered:
```php
<div class="form-group field-article-tittle required">
  <label class="control-label" for="article-title">Title</label>
  <input type="text" id="article-title" class="form-control" name="Article[title]" value="">
  <p class="help-block">Textfield Hint</p>
  <p class="help-block help-block-error"></p>
</div>

<div class="form-group field-article-active">
  <div class="checkbox">
    <label for="article-active">
      <input type="hidden" name="Article[active]" value="0">
      <input type="checkbox" id="article-active" name="Article[active]" value="1" checked="">Active
    </label>
    <p class="help-block help-block-error"></p>
    <p class="help-block">Checkbox Hint</p>
  </div>
</div>
```

For the text field, the p.help-block-error comes after the hint and for the checkbox, the p.help-block-error comes before the hint.
The generated HTML should be consistent, I mean, blocks should be rendered in the same order.
I'm reporting this because I'm having problems setting the margins for the "p". The hint for a text field appears closer to it then the hint for a checkbox because the p.help-block-error have a margin-bottom that push the hint down.

**Comment by mikehaertl** [comment]
Fixing this would break BC. As a workaround you could override the `template` when creating the `ActiveForm`:

```
<?= ActiveForm::begin($action, 'post', [
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{error}\n{hint}"
```

**Comment by marqu3s** [comment]
Unfortunately this doesn't work, at least how I need it.

If I use  "{label}\n{input}\n{error}\n{hint}" as suggested, it changes the order of the rendered tags for the input type=text so they are rendered like the checkboxes.

But when I try "{label}\n{input}\n{hint}\n{error}", this doesn't affect the checkbox rendering. It continues to render the error before the hint.

**Comment by mikehaertl** [comment]
Ah, right, I meant the different checkbox and radio templates. See http://www.yiiframework.com/doc-2.0/yii-bootstrap-activefield.html. You can also override them in the `ActiveForm::begin()` call.

**Comment by marqu3s** [comment]
That worked!
Thanks for this great tip!
