### ISSUE TITLE
[Enh] Html::row() and Html::col() methods.

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2-bootstrap#134]
I propose to create new methods for the `Html` helper.

```php
Html::row($content = '', $options = []);

Html::beginRow($options = []);

Html::endRow(); // same as Html::endTag('div') or have an static list of all opened rows.

Html::col($cols, $content = '', $options = []); // ej: $cols = ['xs' => 12, 'md' => 6, 'xl' => 3]; 

Html::beginCol($cols, $options = []);

Html::endCol(); // same as Html::endTag('div') or have an static list of all opened cols
```

**Comment by Faryshta** [comment]
I think its much easier to read

```php
Html::beginCol(['xs' => 12, 'md' => 6, 'xl' => 3], ['class' => 'info', 'title' => 'hello world']);
```

Than

```php
Html::beginTag('div', ['class' => 'col-xs-12 col-md-6 col-xl-3 info', 'title' => 'hello world']);
```

and much more dynamic

**Comment by cebe** [comment]
why not write plain HTML?

**Comment by Faryshta** [comment]
@cebe yes its possible to write it in plain HTML. Wouldn't that work any other method defined in the `Html` helper?

And its much easier to work with helpers, for example if you have many columns with the same col configuration.

```
$cols = ['xs' => 12, 'md' => 6, 'xl' => 3];

Html::beginCol($cols);

    //...

Html::endCol();


Html::beginCol($cols);

    //...

Html::endCol();

Html::beginCol($cols);

    //...

Html::endCol();
```

Then when you want to edit the col configuration you just need to change one line and not all of them.

**Comment by freezy-sk** [comment]
@Faryshta this can be done easily in php templates and it can be also done with Smarty or Twig
```php
<?php $cols = ['xs' => 12, 'md' => 6, 'xl' => 3]; ?>
<div class="row">
    <div class="<?= $cols ?>">
        some content
    </div>
    <div class="<?= $cols ?>">
        some content
    </div>
    <div class="<?= $cols ?>">
        some content
    </div>
</div>
```

**Comment by Faryshta** [comment]
@freezy-sk same reasoning as above. All the `yii\bootstrap\Html` methods can be done easily on plain HTML and php, that doesn't mean they are not useful.

**Comment by cebe** [comment]
@Faryshta Html Helper classes are useful to write HTML that contains additional logic. E.g. Html::img() resolves Aliases for the URL. There is no benefit in hiding the HTML behind a lot of helper methods that do nothing except creating the tags from arrays. Its better to write HTML explicitly when no additional logic is involved.

**Comment by Faryshta** [comment]
@cebe well for `Html::row()` i can understand the no additional logic thing since it only adds one class, but `Html::col()` does indeed have aditional logic which is to add css classes dynamically depending on the values sent for each type of col size.

**Comment by klimov-paul** [comment]
The way you describe it - it rather should be a widget then a helper method.

**Comment by samdark** [comment]
Agree with @klimov-paul. It's a good candidate for a widget.

**Comment by samdark** [comment]
I don't think that should be wrapped in PHP.

**Comment by samdark** [comment]
And yes, as @klimov-paul said it's a candidate for a widget but application specific widget that hides the logic inside.

**Comment by Faryshta** [comment]
@samdark @klimov-paul should I make a PR with such widget?

**Comment by samdark** [comment]
I think not. In my opinion it should be application specific.

**Comment by Faryshta** [comment]
@samdark what do you mean application specific? this is the yii2-bootstrap repo, i think that means this is specific for bootstrap

**Comment by samdark** [comment]
I mean that it should not be in the yii2-bootstrap extension itself.

I don't see a good use for it except really complex dynamic parameters which are complex both when implemented as template or as config. Thus, hiding complexity in a widget that is specific to exactly that parameters.
