### ISSUE TITLE
NavBar role="navigation" is unneceseary

### ISSUE THREAD

**Issue by tino415** [yiisoft/yii2-bootstrap#137]
### What steps will reproduce the problem?
Render NavBar widget
### What's expected?
According to [newest aria standard table](https://www.w3.org/TR/html-aria/), not `role="navigation"` attribute
### What do you get instead?
`role="navigation"`

### Additional info

| Q                | A
| ---------------- | ---
| Yii bootstrap vesion       |  2.0.0
| PHP version      |  5.5.9
| Operating system | Ubuntu 14.04 LTS Linux 3.13.0-88-generic x86_64

**Comment by samdark** [comment]
@tino415 can you point to exact place in the spec saying it's unnecessary?

**Comment by tino415** [comment]
There are not `id` but green block notice

```
NOTE
Setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and is not recommended as these properties are already set by the browser.
```

then there is table of structure 
`HTML language`,  
`Default Implicit ARIA semantics - should not be used`,
`ARIA roles, states and properties which may be used`

And line with `nav` looks like this:
`nav`,
`role=navigation`,
`global aria-* attributes`

Also if you use w3c validator, it gives you warning.

**Comment by tino415** [comment]
Ok, there is `id` to the [table](https://www.w3.org/TR/html-aria/#nav)

**Comment by samdark** [comment]
OK. That makes perfect sense.

**Comment by bastardijke** [comment]
Same thing for ActiveForm: [html-aria](https://www.w3.org/TR/html-aria/#form)

w3c validator:
Warning: The **form role** is unnecessary for element **form**.

**Comment by cebe** [comment]
@bastardijke please open a new issue. this comment will likely be forgotten.
