### ISSUE TITLE
Replace dependency

### ISSUE THREAD

**Issue by antonmarin** [yiisoft/yii2-bootstrap#139]
### What steps will reproduce the problem?
view composer.json

### What's expected?
`"twbs/bootstrap:^3.3"`

### What do you get instead?
`"bower-asset/bootstrap": "3.3.* | 3.2.* | 3.1.*"`

### Additional info
There is [bootstrap package](https://packagist.org/packages/twbs/bootstrap) at packagist, so you can use it instead bower package. It removes requirement of fxp/composer-asset-plugin and speeds up installation.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.6
| PHP version      | 5.4
| Operating system | any

**Comment by samdark** [comment]
> It removes requirement of fxp/composer-asset-plugin

No, it does not since all other packages including jQuery is still got via fxp.

But since composer.json is officially maintained, it could be a good idea to use it instead.

**Comment by rob006** [comment]
> But since composer.json is officially maintained, it could be a good idea to use it instead.

It is not good idea. If we have extension `X` that require `bower-asset/Y-bootstrap-widget` that depends (in `bower.json`) on `bootstrap` bower package, you will have two installed bootstrap packages - first from composer package, second from bower package. And this could be different and incompatible versions of bootstrap. It is better to stick to one package manager for frontend dependencies.

**Comment by antonmarin** [comment]
1. Version will be the same as managers use same repository. 
2. Some time you will have two packages installed, but right now you can get the same situation if you use extension `x` that require `twbs/bootstrap`

**Comment by samdark** [comment]
OK. @rob006 is right. It's not really a good idea.

@antonmarin version would be the same but package will be different. If two extensions are requiring bootstrap package from bower, only one instance will be installed.

**Comment by antonmarin** [comment]
i mean that if other package requires `twbs/bootstrap` so there would be two instances any way. For example `pckg/frontend` or any other bootstrap theme, that uses exact `twbs/bootstrap`. So i think that rob's situation is an other side of same coin.

As i see, there are some pros and cons:
pros: faster installation, no requirement for fxp(exact at this part)
cons: packages, that use `bower-asset` would install second instance (now packages, that use `twbs` install second instance)

So, there is a second installation of bootstrap anyway till bootstrap use only one package manager.

**Comment by rob006** [comment]
> i mean that if other package requires twbs/bootstrap so there would be two instances any way. For example pckg/frontend or any other bootstrap theme, that uses exact twbs/bootstrap.

This only proving that using composer packages for manage frontend dependencies is wrong - if extensions and themes will use bower packages, this problem will not exist at all.

**Comment by antonmarin** [comment]
We cann't affect usage. But we can use it to our profit. 
Yii main package manager is composer, not bower, thats why i think, that using it is better solution, that bower while there is no divide to frontend/backend.

P.S. Of couse services architecture looks good, and when you have separated server based on node.js, using bower is rather comfortable, but when your architecture is more complex it is not so usable. You generate Html from backend and you have to register scripts at your application assets registry. So frontend and backend mixes, and using only one package manager gives you some profits.

**Comment by rob006** [comment]
> So frontend and backend mixes.

That is why PHP packages (backend) can depend on bower packages (frontend). You can't use composer for managing all frontend dependencies, so you need bower anyway. What is the profit of mixing two package managers for the same thing? This create only problems with dependencies.

**Comment by antonmarin** [comment]
We already have two package managers and there is no way to fix it, so we can just use its profits. 

P.S. I have already said:
> ... till bootstrap use only one package manager.

**Comment by rob006** [comment]
> We already have two package managers

We use only one package manager for frontend dependencies and right now it is bower. And as long as we keep it consistently, there will be no problems with unresolved or duplicated dependencies. 

In fact you suggest an approach that can cause problems, and argue that the themes and extensions can use this (problematic) approach anyway. But this is not a real argument, extensions and themes can make a lot of mistakes and use bad solutions, but it does not change the fact that the official extensions should be treated as a model and use safer solutions.

**Comment by antonmarin** [comment]
> We use only one package manager

It is true if you mean that we=yiisoft, but there are other packages, that could be used and depends on twbs. I have already shown an example.

> use this (problematic) 

Have you tested to say that it is problematic?

> use safer solutions.

So you say, that bootstrap at packagist is less safer, that bootstrap at bower? Really? 

I have nothing to add. I heard you opinion, mine is different. Let @samdark decide.

**Trying to resume:**
- @rob006 says, that frontend should use bower because using composer can cause duplication of packages (correct me if i am wrong) and leading problems
- I agree with @rob006, but right now we have this trouble anyway because bootstrap use packagist and bower at same time. So we can use packagist for own profits (main package manager, much faster installation)

**Comment by rob006** [comment]
> So you say, that bootstrap at packagist is less safer, that bootstrap at bower? 

I say that using one package manager for frontend dependencies is safer than mixing two package managers for the same thing. We can not force PHP world to using one approach, but at least we can create convention for "yii world", so installing two yii extension will not result installing the same package twice, because one extension using composer bootstrap, and second using bower widget that depends on bower bootstrap.

**Comment by antonmarin** [comment]
I understood it long time ago.

**Comment by samdark** [comment]
The convention is to be defined for the common usage of the client side packages. Bower has all packages, composer — only a few. For example, jQuery would never be available via composer officially. That's why, I think, we'll stick with bower.

**Comment by samdark** [comment]
Performance is another matter and there's a good progress about it. See issues in fxp repository.

**Comment by antonmarin** [comment]
What about sign it in guide? Or maybe there is some convention?

**Comment by samdark** [comment]
It's already there: http://www.yiiframework.com/doc-2.0/guide-structure-extensions.html#dependencies

**Comment by antonmarin** [comment]
Thanks.
