### ISSUE TITLE
Nav uses "incorrect" HTML for caret

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-bootstrap#143]
Currently `yii\bootstrap\Nav` uses the following default HTML for Bootstrap caret:
```HTML
<b class="caret"><b>
```
This is not in line with Bootstrap spec itself (see http://getbootstrap.com/css/#helper-classes-carets) and also inconsistent with (correct) HTML used in `yii\bootstrap\ButtonDropdown`:
```PHP
} else { 
$label .= ' <span class="caret"></span>'; 
$options = $this->options; 
```

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2-bootstrap/commit/124848377d7c7a03bde51f70c2aca4c111fcb10b. Thanks!
