### ISSUE TITLE
Inconsistent naming: dropdown vs. dropDown

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-bootstrap#147]
Throughout yii2-bootstrap code methods and variable names use `dropdown` word in all lowercase:
`yii\bootstrap\Dropdown`, `yii\bootstrap\ButtonDropdown`, `ButtonDropdown::$dropdown`, `ButtonDropdown::renderDropdown()`, `Tabs::renderDropdown()`.

Only `yii\bootstrap\Nav` breaks this consistency with `yii\bootstrap\Nav::$dropDownCaret` and `dropDownOptions`. IMO these uses should be renamed even though it will be BC breaking.

**Comment by samdark** [comment]
Could be done in 2.1.
