### ISSUE TITLE
Bootstrap 4 dropped has-error in favor of has-danger. Forms do not yet reflect this.

### ISSUE THREAD

**Issue by ncramer** [yiisoft/yii2-bootstrap#151]
Note: Specific to Bootstrap 4 -- Not sure if this is an appropriate time / place to submit issues, please advise if similar items should be directed elsewhere

bower-asset/bootstrap           v4.0.0-alpha.3
yiisoft/yii2-bootstrap              2.1.x-dev c048258

### What steps will reproduce the problem?
Trigger a form error 

### What's expected?
A styled error message

### What do you get instead?
An unstyled error message

### Additional info

Temporary solution?

Add custom errorCssClasses for has-danger to override has-error:
```
<? $form = ActiveForm::begin([
    ...
    'errorCssClass' => 'has-danger'
    'errorSummaryCssClass' => 'alert alert-danger',
    ...
]); ?>

```
Update help block CSS to include styles similar to has-error, for has-danger
```
.has-danger .control-label,
.has-danger .help-block,
.has-danger .form-control-feedback {
    color: #d9534f;
}
```

I believe there is more involved in the correct solution, but this may work as a holdover.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.6.7
| Operating system | OSX 10.11.6

**Comment by ncramer** [comment]
@cebe , thanks for categorizing. In hindsight, this may not be a yiisoft issue, since I'm actually using kartik's ActiveForm. I assume he is relying on the core code, and that's where this code originates, but before you put effort in, you may wish to have me redirect the issue his way.

**Comment by samdark** [comment]
It's already there in 2.1 branch: https://github.com/yiisoft/yii2-bootstrap/blob/2.1/ActiveForm.php#L87
