### ISSUE TITLE
Bootstrap 4 instead 3

### ISSUE THREAD

**Issue by fbarrento** [yiisoft/yii2-bootstrap#153]
### What steps will reproduce the problem?
1. install yii2-boostrap from composer

### What's expected?
1. boostrap 3 installed

### What do you get instead?
bootstrap 4 installed

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by cebe** [comment]
what are your version constraints for yii2-bootstrap and what is your stability setting?

**Comment by fbarrento** [comment]
In my extension yii2-bootstrap is getting installed by yii2-gii:
`"yiisoft/yii2-bootstrap": "~2.0",`
with stability set to dev

**Comment by cebe** [comment]
`~2.0` includes also `2.1` which will have bootstrap 4, if you want to stick with 2.0.* you have to use `~2.0.0` constraint.
