### ISSUE TITLE
Extending Navbar class results in double navbars

### ISSUE THREAD

**Issue by jeesus** [yiisoft/yii2-bootstrap#154]
### What steps will reproduce the problem?

Create a custom component extending the `yii\bootstrap\NavBar` class. Call it in the view.
### What's expected?

Expected to render a normal navbar with slightly modified content.
### What do you get instead?

Another `<nav id="w0"  class="navbar navbar-inverse navbar-fixed-top" role="navigation">` inside innerContainer after `.navabr-header`.
### Additional info

I've overwritten bootstrap classes previously without any problems. Is there a workaround for this? I just need to add another element after `.navbar-brand`. This happens even when I don't modify the code. E.g just copy-paste init() method from the source.

| Q | A |
| --- | --- |
| Yii vesion | 2.0.8 |
| PHP version | 5.5.34 |
| Operating system | Ubuntu 12.04 |

**Comment by samdark** [comment]
Please show how you've extended it and what you've expected.

**Comment by jeesus** [comment]
```
class NavBar extends \yii\bootstrap\NavBar {
    public function init()
    {
        parent::init();
        $this->clientOptions = false;
        if (empty($this->options['class'])) {
            Html::addCssClass($this->options, ['navbar', 'navbar-default']);
        } else {
            Html::addCssClass($this->options, ['widget' => 'navbar']);
        }
        $options = $this->options;
        $tag = ArrayHelper::remove($options, 'tag', 'nav');
        echo Html::beginTag($tag, $options);
        if ($this->renderInnerContainer) {
            if (!isset($this->innerContainerOptions['class'])) {
                Html::addCssClass($this->innerContainerOptions, 'container');
            }
            echo Html::beginTag('div', $this->innerContainerOptions);
        }
        echo Html::beginTag('div', ['class' => 'navbar-header']);
        if (!isset($this->containerOptions['id'])) {
            $this->containerOptions['id'] = "{$this->options['id']}-collapse";
        }
        echo Html::beginTag("div");
        echo "mydivcontent";
        echo Html::endTag("div");
        echo $this->renderToggleButton();
        if ($this->brandLabel !== false) {
            Html::addCssClass($this->brandOptions, ['widget' => 'navbar-brand']);
            echo Html::a($this->brandLabel, $this->brandUrl === false ? Yii::$app->homeUrl : $this->brandUrl, $this->brandOptions);
        }
        echo Html::endTag('div');
        Html::addCssClass($this->containerOptions, ['collapse' => 'collapse', 'widget' => 'navbar-collapse']);
        $options = $this->containerOptions;
        $tag = ArrayHelper::remove($options, 'tag', 'div');
        echo Html::beginTag($tag, $options);
    }
}
```

As you can see from the images below, the extended class adds extra `nav` tag inside `.navbar-collapse`.

[Original NavBar](https://postimg.org/image/u2io6u0gp/)
[Extended NavBar](https://postimg.org/image/tohc78gd5/)

**Comment by jeesus** [comment]
Any solution? The navbar gets messed up even without altering original code.

**Comment by dynasource** [comment]
not yet. The navbar widget has to be rewritten into a version without `echo` so it can be more easily extended.

**Comment by samdark** [comment]
Try not calling `parent::init();` btw.

**Comment by jeesus** [comment]
@samdark yeah, leaving `parent::init();` out works, but assumes that `$options["id"]` is set when calling the widget. Thanks!
