### ISSUE TITLE
Nav items lose manually set `active` flag when `Nav::activateItems` is false

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-bootstrap#162]
### What steps will reproduce the problem?
```PHP
	<?= Nav::widget([
		'options' => ['class' => 'nav navbar-nav'],
		'activateItems' => false,
		'items' => [
			[
				'label' => 'Item1',
				'url' => ['some/route1'],
				'active' => true,
			],
			[
				'label' => 'Item2',
				'url' => ['some/route2'],
			],
		],
	]) ?>
```
### What's expected?
`Item1` is rendered with `active` CSS class.
### What do you get instead?
No `active` CSS class on `Item1`.
### Additional info
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| yii2-bootstrap | dev-master

**Comment by samdark** [comment]
Fixed.

**Comment by samdark** [comment]
@PowerGamer1 covered more cases: https://github.com/yiisoft/yii2-bootstrap/commit/234ccf6a4c551375291beb986a3a3e48ff10668c

**Comment by PowerGamer1** [comment]
@samdark 
You fixed it only for top level menu items. For all lower level menu items manually set `active` flag is still ignored.

**Comment by PowerGamer1** [comment]
@cebe 
I assume you reopened this issue because of my previous comment. That comment is displayed by GitHub in wrong chronological order. The comment was made before samdark "covered more cases" in commit https://github.com/yiisoft/yii2-bootstrap/commit/234ccf6a4c551375291beb986a3a3e48ff10668c and closed the issue. I will be closing this issue but fell free to reopen it if you think there is anything else to do here.
