### ISSUE TITLE
yii\bootstrap\Nav isItemActive doesn't work with implied /index

### ISSUE THREAD

**Issue by adhayward** [yiisoft/yii2-bootstrap#167]
If you have the following in your view:
```
<?= Nav::widget([
            'activateItems'=>true,
            'items' => [
                [
                    'label' => 'Item 1',
                    'url' => ['/item1/index'],
                ],
                [
                    'label' => 'Item 2',
                    'url' => ['/item2'],
                ],
            ],
        ]); ?>
```
If you click on Item 1 isItemActive returns true and it gets highlighted correctly.
If you click on Item 2 isItemActive returns false and it doesn't get highlighted.

The problem appears to be on the line
`if (ltrim($route, '/') !== $this->route) {`
where $route includes the /index and $this->route doesn't

**Comment by machour** [comment]
Same as #209
