### ISSUE TITLE
Add ability to use a brandImage with the navbar

### ISSUE THREAD

**Issue by Ariestattoo** [yiisoft/yii2-bootstrap#171]
Bootstrap Navbar allows the use of an image in the navbar instead of txt
http://getbootstrap.com/components/#navbar-brand-image

Simple addition of the property and code allows this enhancement,  I have a fix to push however it does dig the hole deeper for issue #164 
http://getbootstrap.com/components/#navbar-brand-image

```php
 if ($this->brandImage !== false) {
            Html::addCssClass($this->brandOptions, ['widget' => 'navbar-brand']);
            echo Html::a(Html::img($this->brandImage), $this->brandUrl === false ? Yii::$app->homeUrl : $this->brandUrl, $this->brandOptions);
        }
```

| Q                | A
| ---------------- | ---
| Yii vesion       |2.1
| PHP version      |7.1
| Operating system |Ubuntu 16.04

**Comment by razvanphp** [comment]
I want to prepare a PR for extending this part of the code, in my case I would like to add some HTML search form in `navbar-header` div, currently this is not configurable, can you please advise how to do it?

Should I create a new property `$headerContent`? Or make the whole brand part configurable, so we can use link, image or custom HTML?

**Comment by cebe** [comment]
I'd add both, `$brandImage` and `$headerContent`.

`$brandImage` will override `$brandLabel` if set and render a link with an image instead of label.

`$headerContent` will be rendered after the `navbar-brand`.
