### ISSUE TITLE
Modal inside ActiveForm not closing when clicking on overlay 

### ISSUE THREAD

**Issue by niklaswolf** [yiisoft/yii2-bootstrap#185]
When I render a modal inside a ActiveForm, the modal can't be closed by clicking on the background/overlay. When the modal is rendered outside of the ActiveForm, everything works fine!
Here's the markup:
```php
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']])
    ...
    Modal::begin([
			'header' => 'Some title',
			'size' => Modal::SIZE_LARGE,
			'toggleButton' => [
				'label' => "More info",
				'class' => 'btn btn-sm btn-info'
			]
		]);?>
		<div class="info-content">
			...
		</div>
   <?php Modal::end();
   ...
ActiveForm::end()?>
```

**Comment by samdark** [comment]
Any errors in browser console?

**Comment by dynasource** [comment]
you should not put Modals inside forms. It should be the other way around, as Modals can be prepended or appended to the DOM.

**Comment by niklaswolf** [comment]
I don't completely agree with this answer... Why shouldn't I generally want to do this? Let's say there's my case where I want to have a "Additional Info"-button next to a form-field to show some additional information for this field in a modal. I think this is a real usecase to do so... Or did I misunderstand your answer?

**Comment by dynasource** [comment]
no worries. You're right about your 'additional info' example. That's a valid usecase. What I meant was that one should not wrap input elements inside a `form` with a `modal`
