### ISSUE TITLE
Tabs: set first visible tab as active if not active set

### ISSUE THREAD

**Issue by nilsburg** [yiisoft/yii2-bootstrap#186]
### What steps will reproduce the problem?
```php
echo \yii\bootstrap\Tabs::widget([
        'items'=>[
            [
                'label'       => 'Tab 1',
                'content'     => 'some content',
                'visible'     => false
            ],
            [
                'label'       => 'Tab 2',
                'content'     => 'some content',
                'visible'     => true
            ],
            [
                'label'       => 'Tab 3',
                'content'     => 'some content',
                'visible'     => true
            ],
        ]
    ]);
```

### What's expected?
Tab 2 should be active
### What do you get instead?
No active tab. 
I am not sure if this is on purpose, but I think that if no active tab is set, the first visible tab should be active.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.11.2
| PHP version      |5.6
| Operating system |Ubuntu 16.04

**Comment by cebe** [comment]
fixed by #187
