### ISSUE TITLE
Alert message does not appear

### ISSUE THREAD

**Issue by grd16** [yiisoft/yii2-bootstrap#190]
### What steps will reproduce the problem?
Using Alert widget from yiisoft/yii2-bootstrap 2.1 and Bootstrap alpha v4.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.6.10
| Operating system | macOS Sierra

**Comment by simialbi** [comment]
Can be closed:
See http://demo.karlen.li/web/
