### ISSUE TITLE
Unable to delete dropdown-menu class in yii\bootstrap\Nav::widget

### ISSUE THREAD

**Issue by xr0m3oz** [yiisoft/yii2-bootstrap#191]
Can I override this in yii\bootstrap\Nav::widget ?

```php
		[
			'label' => 'Test',
			'dropDownOptions' => ['class'=>'11'], //olways add dropdown-menu class
			'url' => ''
		]
```

https://github.com/yiisoft/yii2-bootstrap/blob/master/Dropdown.php#L81

**Comment by samdark** [comment]
Why do you need to delete it? It's required as far as I understand.

**Comment by xr0m3oz** [comment]
I would like to be able to redefine this style.
But dropDownOptions does not allow this, it only adds a class, but does not overwrite this

**Comment by samdark** [comment]
"dropdown-menu" class is semantically correct so I think the right way to customize it is with a more specific selector overriding default styles.

Thanks for proposal but it won't be changed.
