### ISSUE TITLE
No spacing between ".form-groups" in inline form

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-bootstrap#193]
According to http://getbootstrap.com/css/#forms-inline the controls inside inline forms are supposed to be spaced with whitespace characters.

Current Yii2 behavior - incorrect rendering of inline form (no spacing before "Owner email" label and before "Search" button):
![no-space](https://cloud.githubusercontent.com/assets/8275897/24836589/34dd5fce-1d28-11e7-88e5-87b7fe35d874.png)

Expected correct rendering (with spacing before "Owner email" label and before "Search" button):
![spaced](https://cloud.githubusercontent.com/assets/8275897/24836590/34e3bdc4-1d28-11e7-846b-068a97df8fe4.png)

**Comment by mikehaertl** [comment]
@PowerGamer1 Couldn't you simply add the spaces in your form code?

**Comment by PowerGamer1** [comment]
Yep, that would definitely work, not sure why I did not realize this myself.
