### ISSUE TITLE
ActiveForm role="form" is unneceseary

### ISSUE THREAD

**Issue by bastardijke** [yiisoft/yii2-bootstrap#196]
### What steps will reproduce the problem?
Rendering ActiveForm

### What's expected?
According to [aria standard table](https://www.w3.org/TR/html-aria/#form), no `role="form"` attribute

### What do you get instead?
`<form role="form">`

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11
| Yii bootstrap vesion       | 2.0.6
| PHP version      | 7.0.15
| Operating system | Ubuntu 16.04 x64

**Comment by samdark** [comment]
https://www.w3.org/TR/wai-aria/roles#form

**Comment by mikehaertl** [comment]
LGTM. 

The `role="form"` was used in their reference example for the 3.0.0 release, see here:
https://github.com/twbs/bootstrap/blob/e8a1df5f060bf7e6631554648e0abde150aedbe4/css.html#L1449. It's also no longer there in the later docs now.

**Comment by samdark** [comment]
I see. Seems to be unnecessary indeed...
