### ISSUE TITLE
Подгружается twitter bootstrap v4 alpha. Соответственно ломается верстка

### ISSUE THREAD

**Issue by kowap** [yiisoft/yii2-bootstrap#205]

**Comment by samdark** [comment]
Please provide your composer.json.

**Comment by kowap** [comment]
https://pastebin.com/wV58HbgS

**Comment by kowap** [comment]
https://www.dropbox.com/s/ftrx1lx525nkhej/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-06-21%2008.07.19.png?dl=0

https://www.dropbox.com/s/ftrx1lx525nkhej/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-06-21%2008.07.19.png?dl=0
Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)

**Comment by kowap** [comment]
ааа, у меня почему то в **vendor/yiisoft/yii2-bootstrap/composer.json** прописано **"bower-asset/bootstrap": "~4.0.0@alpha"**

**Comment by kowap** [comment]
```
composer require yiisoft/yii2-bootstrap
Using version ^2.0 for yiisoft/yii2-bootstrap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals       
  - Installing bower-asset/bootstrap (v4.0.0-alpha.6) Downloading: 100%         
  - Installing yiisoft/yii2-bootstrap (2.1.x-dev 8d53c44) Cloning 8d53c440b4 from cache
Writing lock file
Generating autoload files

```
все удалил почистил кэш компосера.

**Comment by samdark** [comment]
Пропишите `~2.0.0`.

**Comment by kowap** [comment]
спасибо большое)
