### ISSUE TITLE
Link to licence information

### ISSUE THREAD

**Issue by AntonyLey** [yiisoft/yii2-bootstrap#206]
The link to the licence information  is broken.

Are you able to tell me the licence for https://github.com/yiisoft/yii2-bootstrap (yiisoft/yii2-bootstrap)?

With thanks in advance,

Antony

**Comment by samdark** [comment]
It's missing indeed. Will add it. The license is BSD 3 clause.

**Comment by AntonyLey** [comment]
Thanks Alexander

*Antony Ley | Information Policy Officer*


*Information Services **Griffith University  *
*| Nathan campus | QLD 4111 | Building location (N53) Room 0.03 T +61 7
3735 5695 | F +61 7 3735 4075 | 0423 425 592| email
**antony.ley@griffith.edu.au
<antony.ley@griffith.edu.au>*

*Griffith Copyright Guides
<https://intranet.secure.griffith.edu.au/copyright-matters/copyright-guide>*

griffith.edu.au <https://www.griffith.edu.au/>


Griffith University - CRICOS Provider Number 00233E



PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the
use of the addressee(s) and may contain information which is confidential
or privileged.  If you receive this email and you are not the addressee or
responsible for delivery of the email to the addressee(s), please disregard
the contents of the email, delete the mail and notify the author
immediately.

On Wed, Jun 21, 2017 at 9:47 PM, Alexander Makarov <notifications@github.com
