### ISSUE TITLE
Cannot use latest version of yii2-debug 

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2-bootstrap#213]
When I use the version 2.1 of yii2-bootstrap I cannot use the latest version of yii2-debug

### What steps will reproduce the problem?
In composer:

```
    "require": {
        "php": ">=7.0.0",
        "yiisoft/yii2": "~2.0.0",
        "yiisoft/yii2-authclient": "~2.1.0",
        "yiisoft/yii2-bootstrap": "~2.1.0@dev",
        "bower-asset/bootstrap": "~4.0.0@beta",
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.11",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
```

### What's expected?

I can only use yii2-debug version 2.0.6

### What do you get instead?

use of yii2-debug version 2.0.11

Here is the error message

```
  Problem 1
    - yiisoft/yii2-bootstrap 2.0.x-dev requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> no matching package found.
    - yiisoft/yii2-debug 2.0.11 requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.x-dev].
    - Installation request for yiisoft/yii2-debug ~2.0.11 -> satisfiable by yiisoft/yii2-debug[2.0.11].
```

[edit @schmunk42: formatting]

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0
| Operating system | Ubuntu

**Comment by schmunk42** [comment]
It's not possible in the current state of `yii2-debug` to use it with `yii2-bootstrap >= 2.1` (bootstrap@4), see https://github.com/yiisoft/yii2-debug/blob/ccf0e5cc533f26f6151f013e26de452b06662de1/composer.json

We need to introduce a 2.1 branch like `yii2-bootstrap` has and also make some updates there.

**Comment by MattDalm** [comment]
I hear you but what I don't understand is that yii-debug 2.0.6, which is the only on I can use with yii2-bootstrap 2.1 is buggy as well. Since they are both buggy, can we still use the latest version of yii2-debug?

**Comment by samdark** [comment]
Closing it here since it should be solved in yii2-debug.

**Comment by schmunk42** [comment]
This is, because `yii2-debug` got a constraint for `yii2-bootstrap` in 2.0.7. So composer resolves to an old version "containing the bug", this it is missing actually correct constraint.

I'd recommend to use `yii2-debug:^2.0.11` for production sites, but you should be able to install latest `yii2-debug` with an aliased version:

    "yiisoft/yii2-debug": "dev-master as 2.0.999"

**Comment by MattDalm** [comment]
Hi @schmunk42 

Same error using the above

`  Problem 1
    - yiisoft/yii2-bootstrap 2.0.x-dev requires bower-asset/bootstrap 3.3.* | 3.2.* | 3.1.* -> no matching package found.
    - yiisoft/yii2-debug dev-master requires yiisoft/yii2-bootstrap ~2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.x-dev].
    - Installation request for yiisoft/yii2-debug dev-master as 2.0.999 -> satisfiable by yiisoft/yii2-debug[dev-master].
`

**Comment by schmunk42** [comment]
Do you have the asset-plugin installed? If yes, please see https://github.com/fxpio/composer-asset-plugin/issues/86#issuecomment-68347825

There's an issue with downgrading assets.

**Comment by dynasource** [comment]
for those suffering from this issue, you can temporarily use the following config in your composer.json to make the installation pass:
```json
{
//composer.json
  "provide": {
    "bower-asset/jquery": "*",
    "bower-asset/jquery-ui": "*",
    "bower-asset/jquery.inputmask": "*",
    "bower-asset/punycode": "*",
    "bower-asset/yii2-pjax": "*"
  }
}
```
