### ISSUE TITLE
Toggle button position

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2-bootstrap#214]
Regarding v 2.1 using BS4.

In BS4 the toggle button in the navbar is positioned to the right of the brand label however in yii2-bootstrap it is on its left.

### What steps will reproduce the problem?
Use Navbar

### What's expected?
Toggle button to the right when in phone view

### What do you get instead?
Toggle button to the left

Easy fix is to modify the init of navbar.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0
| Operating system | Ubuntu

**Comment by simialbi** [comment]
Can be closed
See: https://github.com/yiisoft/yii2-bootstrap4/issues/25
