### ISSUE TITLE
Breadcrumb in BS4

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2-bootstrap#215]
Regarding version 2.1
Breadcrumb markup changed slightly and now requires class="breadcrumb-item" to each `<li>`

### What steps will reproduce the problem?
use breadrumb

### What's expected?
breadcrumb to be displayed on 1 line

### What do you get instead?
break line between each `<li>`

### Additional info
Fix

```
    /**
     * @var string the template used to render each inactive item in the breadcrumbs. The token `{link}`
     * will be replaced with the actual HTML link for each inactive item.
     */
    public $itemTemplate = "<li class=\"breadcrumb-item\">{link}</li>\n";
    /**
     * @var string the template used to render each active item in the breadcrumbs. The token `{link}`
     * will be replaced with the actual HTML link for each active item.
     */
    public $activeItemTemplate = "<li class=\" breadcrumb-item active\">{link}</li>\n";
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0
| Operating system | Ubuntu

**Comment by machour** [comment]
Implemented in yii2-bootstrap4: https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Breadcrumbs.php#L66

Can be closed
