### ISSUE TITLE
Release date for 2.0.7?

### ISSUE THREAD

**Issue by MarcoMoreno** [yiisoft/yii2-bootstrap#218]
Any chance we can get a release for 2.0.7 soon?  It's been about a year and a half since 2.0.6 and there are some updates that would be nice to use.

Perhaps the few remaining issues could get pushed to 2.0.8?

Apologies if this is not the proper place to raise the question.

**Comment by samdark** [comment]
Released. Announcement will be there soon.

**Comment by MarcoMoreno** [comment]
Thanks for the immediate response, samdark!
