### ISSUE TITLE
Add custom HTML to navbar-header

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2-bootstrap#219]
For example, mobile search form:

<img width="395" alt="screen shot 2017-10-19 at 10 42 08" src="https://user-images.githubusercontent.com/4599319/31762029-43b0258e-b4ba-11e7-9a7d-0a3b7a949615.png">

I'm preparing a PR for this, needed issue number.

**Comment by samdark** [comment]
Next time you can reuse PR number by opening it and then adding one more commit.
