### ISSUE TITLE
yiisoft/yii2-bootstrap 2.0.0 requires bower-asset/bootstrap 3.2.* | 3.1.* -> no matching package found

### ISSUE THREAD

**Issue by Cuihongsen** [yiisoft/yii2-bootstrap#226]
### What steps will reproduce the problem?
composer 安装的时候
yiisoft/yii2-bootstrap 2.0.0 requires bower-asset/bootstrap 3.2.* | 3.1.* -> no matching package found
### What's expected?
fx插件版本1.4.2
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.13
| PHP version      |7.0
| Operating system |centos 7

另外，我非常讨厌这个fx插件，就不能把这个恶心的的东西去除吗

**Comment by Cuihongsen** [comment]
我的composer.json
{
    "name": "11111",
    "description": "11111",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.11111.11111/",
    "type": "project",
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.13",
        "yiisoft/yii2-bootstrap": "~2.0.7",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-redis": "~2.0.6",
        "yiisoft/yii2-mongodb": "~2.1.2",
        "yiisoft/yii2-elasticsearch": "~2.0.4@dev",
        "imagine/imagine": "~0.5.0",
        "yiisoft/yii2-imagine": "^2.0@dev",
        "robregonm/yii2-pdf": "~1.0.3",
        "phpoffice/phpexcel": "^1.8",
        "weyii/yii2-filesystem": "^2.0",
        "aliyuncs/oss-sdk-php": "~2.0.0",
        "aodto/phasher": "dev-master@dev",
        "overtrue/wechat": "^3.3",
        "graphp/graphviz": "^0.2.1",
        "php-ffmpeg/php-ffmpeg": "^0.9.5",
        "filsh/yii2-oauth2-server": "~v2.0.0",
        "bazilio/yii2-async": "^0.2.0",
        "yiisoft/yii2-queue": "^2.0",
        "yiisoft/yii2-httpclient": "^2.0",
        "phpseclib/mcrypt_compat": "^1.0",
        "sunra/php-simple-html-dom-parser": "^1.5",
        "yii2mod/yii2-sweet-alert": "^1.3",
        "npm-asset/bootstrap-sweetalert": "^1.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/codeception": "2.1.*"
    },
    "config": {
        "process-timeout": 1800,
        "preferred-install": "dist",
        "secure-http": false
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }
}

**Comment by samdark** [comment]
You should have either asset-packagist in your application composer.json or composer asset plugin installed globally.
