### ISSUE TITLE
Modal window header have wrong order and code

### ISSUE THREAD

**Issue by Alex-Bond** [yiisoft/yii2-bootstrap#229]
### What steps will reproduce the problem?

Try to create the modal window with ```\yii\bootstrap\Modal``` widget.

### What's expected?
Close button on the right side.

### What do you get instead?
Close button on left side.

### Additional info

To fix it you need to adjust to new code style modal-header.
http://getbootstrap.com/docs/4.0/components/modal/

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13.1
| PHP version      | 7.2.1
| Operating system | MacOS

**Comment by simialbi** [comment]
Can be closed. Rendering got fixed.
https://github.com/yiisoft/yii2-bootstrap4/blob/8fbf92295f85e0f5817af13001e05a1b37f82fdf/tests/ModalTest.php#L72 proves this
