### ISSUE TITLE
Update 2.1 branch

### ISSUE THREAD

**Issue by cluwong** [yiisoft/yii2-bootstrap#234]
Is there an estimation when branch 2.1 will be updated to include latest changes in 2.0 branch?
I'm working on a template that uses BS4. However my project (currently using BS3 template) uses bootstrap widgets with new some options not available in 2.1 branch and breaks when switching to the 2.1 branch.

**Comment by klimov-paul** [comment]
I am sorry, but I am unable to do this. I am not aware of the changes Bootstrap 4 brings and not a CSS expert. Thus I will be unable to resolve code conflicts, which will appear during the merge - I simply unable to decide which code is correct and which is not.

If you DO care about this, you can perform merge yourself:

- make a fork of the project
- run `git fetch`
- checkout branch '2.1'
- pull changes from `upstream master` resolving code conflicts
- open a pull request with your changeset against branch '2.1' (select it in drop-down)

in case a solid pull request with readable diff will be present, me and my coleages will be able to merge it inside '2.1'.

**Comment by schmunk42** [comment]
Please see also https://github.com/yiisoft/yii2-bootstrap/issues/77#issuecomment-369005748

**Comment by cjtterabyte** [comment]
Hi, please delete brach 2.1 --> BS4, so there are no conflicts and you can install BS3 yiisoft/yii2-bootstrap, BS4 and yiisoft/yii2-bootstrap4 simultaneously.

**Comment by samdark** [comment]
You cannot anyway because it's not possible to install two versions of the same package via asset-packagist or fxp.

**Comment by machour** [comment]
This issue can be closed & branch 2.1 should be removed.
We now have yii2-bootstrap4 and yii-bootstrap4
