### ISSUE TITLE
Move bower to npm branch master.

### ISSUE THREAD

**Issue by cjtterabyte** [yiisoft/yii2-bootstrap#239]
Yii: 2.0.15.1
Php: 7.1.17.
Centos 7.1

Branch 2.2:

    composer.json:

    "require": {
        "yiisoft/yii2": "2.1.x-dev",
        "yiisoft/yii2-jquery": "1.0.x-dev",
        "npm-asset/bootstrap": "3.3.* | 3.2.* | 3.1.*"
    },

Branch Master:

    composer.json:

    "require": {
        "yiisoft/yii2": "~2.0.6",
        "bower-asset/bootstrap": "3.3.* | 3.2.* | 3.1.*"
    },

We must unify BS3 to npm-asset/bootstrap

**Comment by rob006** [comment]
> We must unify BS3 to npm-asset/bootstrap

Why?

**Comment by cjtterabyte** [comment]
@rob006 Because you already have npm-asset/bootstrap in BS3 for yii2.1, and for yii 2.0 you have it in bower-asset/bootstrap, the idea is to unify the BS3 asset directory, since you can have an installation with a theme in BS4 , and extension that use BS3, giving conflict in the installation when you use yii 2.0, instead when you have it in yii 2.1. There will be no problem because BS4 is installed in bower-asset/bootstrap, and BS3 is installed in npm-asset/bootstrap.

**Comment by cjtterabyte** [comment]
I really do not understand having an extension of boostrap3 and bootstrap4, in the same directory makes it impossible to use them together unfortunately all the official extensions do not offer boostrap4, so because I do not standardize the dependencies in the same directory to be able to install them without conflicts I do not really understand it, It is easier to say no, to analyze the why of things, they are only my two cents.

**Comment by schmunk42** [comment]
@cjtterabyte You may read this issue for some more details: https://github.com/yiisoft/yii2-bootstrap/issues/221

In fact we have to get rid of assets completely (by default) - composer will never be able to install two versions of a package like npm or yarn can.
