### ISSUE TITLE
Double encoded URL in Nav widget

### ISSUE THREAD

**Issue by Dorbah** [yiisoft/yii2-bootstrap#244]
### What steps will reproduce the problem?
Nav.php: Line 204:
return Html::tag('li', Html::a($label, $url, $linkOptions) . $items, $options);

### What's expected?
http://localhost/index.php?r=jobs/index

### What do you get instead?
http://localhost/index.php?r=jobs%2Findex

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.15.1
| PHP version      |  7.1.6
| Operating system | Windows 10 Pro

**Comment by rob006** [comment]
It is not double ecoded. It is just encoded.

**Comment by samdark** [comment]
That's expected.
