### ISSUE TITLE
Autohide alerts widget, new propert autohide

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-bootstrap#25]
Autohide alerts widget, new propert autohide

I think the alerts are ideas to display flash messages, and other uses.

Could have a autohide property of the type that receives a whole number in seconds. By default could do a jquery fade or on the property autohide be of type array, which receives: Time in seconds and effect (hide, slide, fade ...)

Let me know the opnion of the community please!

Hugs You!

**Comment by samdark** [comment]
It could be implemented in project CSS. I don't think it worth adding to the class properties.
