### ISSUE TITLE
Collapse widget issue

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2-bootstrap#253]
### What steps will reproduce the problem?
echo Collapse widget

### What is the expected result?
Collapsed headings should contain `collapsed` class in `a` tag

### What do you get instead?
The class appears in the tag only after any of the panels is opened

### Additional info
I replaced this:
```php
$itemToggleOptions = array_merge([
    'tag' => 'a',
    'data-toggle' => 'collapse',
], $this->itemToggleOptions);
Html::addCssClass($itemToggleOptions, ['widget' => 'collapse-toggle']);
```

with the following code
```php
$active = false;
if (isset($options['class'])) {
    $classes = is_string($options['class']) ? explode(' ', $options['class']) : $options['class'];
    $active = in_array('in', $classes);
}

$itemToggleOptions = array_merge([
    'tag' => 'a',
    'data-toggle' => 'collapse',
], $this->itemToggleOptions);
Html::addCssClass($itemToggleOptions, ['widget' => 'collapse-toggle']);

if (!$active) {
    Html::addCssClass($itemToggleOptions, ['collapsed' => 'collapsed']);
}
```
and now it works like a charm

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 7.3.2
| Operating system | Mac OS X Mojave

**Comment by evil1** [comment]
@samdark Should I create a Pull Request for this bug?

**Comment by samdark** [comment]
Yes, please.

**Comment by evil1** [comment]
@samdark А по русски тут можно писать? Или в силу того, что есть иностранные участники коммьюнити, лучше писать на английском?

**Comment by samdark** [comment]
Лучше на английском. Меня можно поймать в Slack или в Telegram, если хочется пообщаться.

**Comment by evil1** [comment]
@samdark Slack не использую :( Номер телефона подскажешь в Telegram?
