### ISSUE TITLE
bootstrap widget não mapeado: labels

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-bootstrap#26]
We can have a widget to bootstrap label?

THE place to write this, for example:

´´
http://getbootstrap.com/components/#labels
´´

Could Write this:

echo Label::widget( [ 'Order Open', 'default' ] );
echo Label::widget( [ 'BlackFriday Day', 'primary' ] );
echo Label::widget( [ 'Vip Client', 'success' ] );

or

echo Label::widget([
     [ 'Order Open', 'default' ],
     [ 'BlackFriday Day', 'primary' ],
     [ 'Vip Client', 'success' ] 
]);

AS advantages I see:

1 - encapsulate another native bootstrap component as widget, avoiding use native code html / css / js expalhados the views.

2 - Item 1 provides the safety switch to bootstrap 4, 5 ... 10 for example, over the years, ensuring that almost no or little html the views, even q markup change of a label, as in this incapsulada component widget bootstrap package, we can develop and build perfect miegação processes.

3 - It is elegant views with little or no text html and css and js own, some thought could be a target almost did not write html, css and js in views, using the maximum YII2.x widgets API

4 - Even with something as trivial, encpsular alone is already an advantage is for compatibility, migration, and code views of beauty or simply by providing a more complete API.

**Comment by lukBarros** [comment]
Before I forget:

This is then apply to badges, panels and other native components unmapped bootstrap

**Comment by lukBarros** [comment]
Before I forget:

If I want to populate a column of gridView with a label that seems very elegant in defining columns of the grid view widget

**Comment by cebe** [comment]
If there is no benefit in abstraction it should be avoided. Its easier to learn if you already know bootstrap and it is more obvious what the output is when you look at the code.
