### ISSUE TITLE
Add support of Bootstrap checkbox/radio toggle buttons to ActiveField

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-bootstrap#45]
Migrated from https://github.com/yiisoft/yii2/issues/7519

Add support of [these button groups](http://getbootstrap.com/javascript/#buttons-checkbox-radio) to bootstrap/ActiveField.

**Comment by SilverFire** [comment]
Will it be merged?

**Comment by klimov-paul** [comment]
Resolved by #46
