### ISSUE TITLE
allow to set bower-asset/bootstrap specific version

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2-bootstrap#62]
since bower-asset/bootstrap v3.3.5, I have those weird warnings

```js
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff2
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.ttf
```

turn out it involves some political issue which affects lot of people out there

https://github.com/twbs/bootstrap/issues/16708
https://github.com/twbs/bootstrap/pull/16359
https://github.com/twbs/bootstrap/issues/16663

I really dont know how to make yii2-bootstrap use bower-asset/bootstrap v3.3.4, or even better, use the original bootstrap package [twbs/bootstrap] ( https://packagist.org/packages/twbs/bootstrap )

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2-bootstrap/issues/54

**Comment by cebe** [comment]
to require a specific version, just add that requirement to your composer.json:

```json
	"require": {
...
		"bower-asset/bootstrap": "3.3.4"
	},
```

as this is a downgrade you may need to remove the vendor dir before running composer update.

**Comment by duynguyen0511** [comment]
thanks alot. You are correct that I have to remove vendor dir to make it work.
