### ISSUE TITLE
Documentation is not in sync with latest release

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2-bootstrap#69]
The class documentation is obviously created from the latest development branch of this extension. This leads to some confusion. For example I've read about the `visible` feature for `yii\bootstrap\Tabs` here:

http://www.yiiframework.com/doc-2.0/yii-bootstrap-tabs.html#$items-detail

So:

1. Documentation should be for the latest stable release
2. The above `visible` feature should get a note like "*since 2.0.5*" or similar.

On a sidenote I wonder, when the next release of this extension is planned.

**Comment by samdark** [comment]
I'd prefer latest stable by default and master for edge users which are many.

**Comment by samdark** [comment]
Release is planned soon.

**Comment by cebe** [comment]
this will be solved when we have the new website.
