### ISSUE TITLE
tabindex="-1" breaks Select2 widgets in yii\bootstrap\Modal

### ISSUE THREAD

**Issue by derekisbusy** [yiisoft/yii2-bootstrap#70]
In yii\bootstrap\Modal the tabindex="-1" option prevents Select2 search input from working.

**Comment by cebe** [comment]
can you elaborate? give a bit more details about what you are doing, which code you are using and what exactly is not working?

**Comment by derekisbusy** [comment]
Yeah I was using kartik-v Select2 widget inside of the bootstrap modal loaded via ajax and the search input for Select2 would not focus.

I fixed it by removing the attribute in JavaScript:
```javascript
$('#modal').removeAttr('tabindex');
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/8708 ?

**Comment by derekisbusy** [comment]
No that's a different issue. I guess the js solution will work for now.

**Comment by AditMulyadi** [comment]
thanks for science

**Comment by tihoho** [comment]
just for example:
```
<? 
Modal::begin([
    'header' => 'Modal Title', 
    'id' => 'modal_id',
    'options' => ['tabindex' => ''],
]); 
?>
```
