### ISSUE TITLE
New installation or update through composer does not include latest files

### ISSUE THREAD

**Issue by HanafiAhmat** [yiisoft/yii2-bootstrap#75]
I tried to update using "composer update" command in the "advance" project folder but i did not get the latest files such as those included in the zip downloads.
The composer.json file already has this line included for bootstrap, `"yiisoft/yii2-bootstrap": "~2.0.0"`.

**Comment by samdark** [comment]
What you're getting is the latest tagged stuff. If you're getting master zip, there are not yet released changes.

**Comment by HanafiAhmat** [comment]
Thank you for the clarification @samdark.
