### ISSUE TITLE
Update `Html::icon` to use different icon font e.g font-awesome

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2-bootstrap#89]
The font-awesome prefixes are `fa fa-`, similar to glyphicon's `glyphicon glyphicon-`. Can the `Html::icon` function be updated to use a custom prefix by default?

**Comment by samdark** [comment]
Yes. You can use DI to set options: http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#practical-usage

**Comment by xjdata** [comment]
set icon prefix  not work
```php
Yii::$container->set('yii\bootstrap\Html\icon', ['prefix' => 'fa fa-']);
```
